-- Kleuren voor gruvbox.
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local background = "rgba(40,40,40,1.0)" -- #282828
local accent = "rgba(215,153,33,1.0)" -- #d79921
local text = "rgba(235,219,178,1.0)" -- #ebdbb2
local border_active = "rgba(d79921ff)" -- bijv. Gruvbox geel
local border_inactive = "rgba(282828ff)" -- Gruvbox achtergrond

hl.config({
    decoration = {
        rounding = 9,
        blur = {
            enabled = true,
        },
        shadow = {
            enabled = false,
        },
        active_opacity = 1.0,
        inactive_opacity = 1.0,
    },
    general = {
        -- Border instellingen
        border_size = 2,
        col = {
            active_border = border_active,
            inactive_border = border_inactive,
        },
    },
})

