--###############
--## MONITORS ###
--###############

-- See https://wiki.hypr.land/Configuring/Monitors/
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local vars = require("vars")

hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = "auto",
})

hl.monitor({
    output = "Virtual-1",
    mode = "1920x1080@60",
    position = "auto",
    scale = "1.2",
})


hl.monitor({
    output = "DP-3",
    mode = "1920x1080@240",
    position = "1920x0",
    scale = "1",
})

hl.monitor({
    output = "HDMI-A-3",
    mode = "1920x1080@60",
    position = "0x0",
    scale = "1",
})

--laptop monitor
hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60",
    position = "1920x0",
    scale = "1",
})

--hdmi via laptop-direct
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60",
    position = "0x0",
    scale = "1",
})

--###############
--##  INPUT   ###
--###############
-- Source: input_devices.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("input_devices")
-- Source: multimedia.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("multimedia")

--##################
--## MY PROGRAMS ###
--##################

-- See https://wiki.hypr.land/Configuring/Keywords/

-- Set programs that you use
local terminal = "kitty"
local menu = "wofi --show drun"
local browser = "waterfox  --new-window\027"

--################
--## AUTOSTART ###
--################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:

-- exec-once = $terminal
-- exec-once = nm-applet &

--############################
--## ENVIRONMENT VARIABLES ###
--############################

-- See https://wiki.hypr.land/Configuring/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XDG_PICTURES_DIR", "/home/joost/Images")

--####################
--## LOOK AND FEEL ###
--####################

-- Source: look-and-feel.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("look-and-feel")
-- Source: gruvbox.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("gruvbox")

--##################
--## KEYBINDINGS ###
--##################

-- Source: keybinds.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("keybinds")

--############
--## INPUT ###
--############

-- https://wiki.hypr.land/Configuring/Variables/#input

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

hl.config({
    input = {
        kb_layout = "us",
        kb_variant = "",
        kb_model = "",
        kb_options = "",
        kb_rules = "",
        follow_mouse = 1,
        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.
        touchpad = {
            natural_scroll = false,
            disable_while_typing = false,
        },
    },
    -- https://wiki.hypr.land/Configuring/Variables/#gestures
    gestures = {
        workspace_swipe_touch = false,
    },
    -- Example per-device config
    -- See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
    --#############################
    --## WINDOWS AND WORKSPACES ###
    --#############################
    -- See https://wiki.hypr.land/Configuring/Window-Rules/ for more
    -- See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules
    -- Example windowrule
    -- windowrule = float,class:^(kitty)$,title:^(kitty)$
    --##################
    --## PERMISSIONS ###
    --##################
    -- See https://wiki.hypr.land/Configuring/Permissions/
    -- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
    -- for security reasons
    -- ecosystem {
    --   enforce_permissions = 1
    -- }
    -- permission = /usr/(bin|local/bin)/grim, screencopy, allow
    -- permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
    -- permission = /usr/(bin|local/bin)/hyprpm, plugin, allow
})

hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("swww-daemon")
    hl.exec_cmd("~/.config/hypr/scripts/random-wallpaper.sh")
    hl.exec_cmd("~/.config/hypr/scripts/battery_notify.sh")
    hl.exec_cmd("/usr/local/bin/pypr")
end)

