-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — top-level key 'preload = /home/joost/Images/wallpapers/Boxes.png' has no enclosing section
-- TODO: manual review — top-level key 'preload = /home/joost/Images/wallpapers/gruv-portal-cake.png' has no enclosing section
-- TODO: manual review — top-level key 'preload = /home/joost/Images/wallpapers/orbit.png' has no enclosing section
-- TODO: manual review — top-level key 'preload = /home/joost/Images/wallpapers/solarsystem.png' has no enclosing section
-- TODO: manual review — top-level key 'preload = /home/joost/Images/wallpapers/space.png' has no enclosing section
-- TODO: manual review — top-level key 'preload = /home/joost/Images/wallpapers/sunset.png' has no enclosing section
-- TODO: manual review — top-level key 'preload = /home/joost/Images/wallpapers/vrouw.png' has no enclosing section
-- TODO: manual review — top-level key 'wallpaper = eDP-1,/home/joost/Images/wallpapers/orbit.png' has no enclosing section
